#!/usr/bin/env bash

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
jvmProps="-XX:+PrintFlagsFinal -XX:+UseLargePages"


hz memberOps "${jvmProps} -Xms2G -Xmx2G ${hzProps}"
hz clientOps "${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hz cluster -size M4C4 -id HZ -v 3.7-SNAPSHOT   -type HZ -boxes a.box

hz memberOps "${jvmProps} -Xms2G -Xmx2G"
hz clientOps "${jvmProps} -Xms1G -Xmx1G"
hz cluster -size M4C4 -id GG -v 1.6.0-SNAPSHOT -type GG -boxes b.box


hz type Metrics
hz driver Client,Member
hz interval 1
hz threads 8
hz warmup 60
hz bench 300

nohup hz run -id HZ setHZ >> outHZ.txt &
nohup hz run -id GG putGG >> outIG.txt &
wait
hz wipe

hz chart compare -dir output -red HZ -blue GG
