#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT


hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
hz memberOps "-Xms2G -Xmx2G ${hzProps}"
hz clientOps "-Xms200M -Xmx400M ${hzProps}"

hz cluster -size M4C4 -v 3.7.1 -boxes a.box

hz driver Member
hz threads 1
hz run load

hz driver Client
hz threads 16
hz bench 2700
hz bounce -iterations 100  -iterationDelay 5 -restartDelay 5 RandomMember &
hz run get