#!/usr/bin/env bash

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true -Dhazelcast.connection.monitor.max.faults=1"
hzCmd set memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms5G -Xmx5G ${hzProps}"
hzCmd set clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms1G -Xmx1G ${hzProps}"

hzCmd init cluster -size XS -id NEW -v 3.7-SNAPSHOT -type HZ -boxes a.box
hzCmd init cluster -size XS -id OLD -v 3.6.2        -type HZ -boxes b.box

hzCmd bench type Metrics
hzCmd bench driver Member
hzCmd bench threads 1
hzCmd bench allowException false
nohup hzCmd bench run -cluster NEW -b loadData -warmup false >> new.out &
nohup hzCmd bench run -cluster OLD -b loadData -warmup false >> old.out &
wait

hzCmd bench driver Client
hzCmd bench threads 32
hzCmd bench duration 300
hzCmd bench allowException true
nohup hzCmd bench run -cluster NEW -b getBench -warmup false >> new.out &
nohup hzCmd bench run -cluster OLD -b getBench -warmup false >> old.out &

for i in {1..3}; do
 sleep 60
 hzCmd bench driver Member${i}
 hzCmd bench threads 1
 hzCmd bench allowException false
 nohup hzCmd bench run -cluster NEW -b shutDown -warmup false >> new.out &
 nohup hzCmd bench run -cluster OLD -b shutDown -warmup false >> old.out &
done

wait
hzCmd wipe
hzCmd chart compare -dir output -red NEW -blue OLD

mv *.out output
