#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT


hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true -Dhazelcast.connection.monitor.max.faults=1"
hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms3G -Xmx3G ${hzProps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms200M -Xmx400M ${hzProps}"
hz cluster -size M4C4 -id NEW -v $(hazelcastVersion) -boxes a.box

hz driver Member
hz threads 1
hz run -id NEW -warmup false loadData

./runGetCheck exitCode.txt &
sleep 20

for j in {1..3}; do

 for i in {1..3}; do
  hz driver Member${i}
  hz threads 1
  hz allowException false
  hz run -id NEW -warmup false shutDown
  sleep 20
  ./checkExitCode exitCode.txt
 done

 for i in {1..3}; do
  hz embeddedRestart -id Member${i}
 done

done
