#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    chartAll-JavaMetrics output
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size M4C4 -v 3.7 -ee -boxes a.box

hz run load
hz run validate
hz run get &
hz bounce -iterations 2  -iterationDelay 900 -restartDelay 900 RandomMember
hz stop
