#!/usr/bin/env bash

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
jvmProps="-XX:+PrintFlagsFinal -XX:+UseLargePages"

hzCmd set jhic
hzCmd set jhicArgs -d 960 -i 1000


hzCmd set memberOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hzCmd set clientOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hzCmd init cluster -size XS -id HZ  -v 3.6.2 -ee true  -type HZ -boxes a.box

hzCmd set memberOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G"
hzCmd set clientOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G"
hzCmd init cluster -size XS -id GG  -v 1.5.0.final     -type GG -boxes b.box

hzCmd bench type Hdr
hzCmd bench driver Client
hzCmd bench threads 8
hzCmd bench interval 1
hzCmd bench warmup 900
hzCmd bench duration 10800
nohup hzCmd bench run -cluster HZ -b setHZ >> hz.out &
nohup hzCmd bench run -cluster GG -b putGG >> gg.out &
wait
hzCmd wipe

hzCmd chart compare -dir output -red HZ -blue GG

hzCmd processJhic -dir output
hzCmd chart compairHdr -dir output -red Member-HZ -blue Member-GG
hzCmd chart compairHdr -dir output -red Client-HZ -blue Client-GG

cp go output/
mv *.out output/