#!/usr/bin/env bash

clients=0
members=4
membersBox=0
outputDir=out2-${clients}c-${members}m-hz-gem-gg

hzCmd listen > detail.out &

./benchHz  ${clients} ${members} ${membersBox} ${outputDir}
./benchGem ${clients} ${members} ${membersBox} ${outputDir}
./benchGg  ${clients} ${members} ${membersBox} ${outputDir}
