#!/usr/bin/env bash

clients=$1
members=$2
membersBox=$3
outputDir=$4

clusterId=F
version=8.2.0
./initGemCluster ${clients} ${members} ${membersBox} ${clusterId} ${version}

benchid=putRegion
clusterName=Gem

hzCmd load -id ${clusterId} -class gem.cache.Put -task ${benchid}

./benchRun ${benchid} ${clusterName}

hzCmd download -dir ${outputDir}/${clusterName}-${version}

hzCmd wipe

