#!/usr/bin/env bash

clients=$1
members=$2
membersBox=$3
clusterId=$4
version=$5

jvmOps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"

clusterType=HZ
./initCluster ${clusterId} ${clusterType} ${version} ${clients} ${members} ${membersBox} ${jvmOps}

