#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4"}
user=${3:-ec2-user}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -ee -size ${size} -v ${hzVersion} -boxes a.box -user ${user}

hz run quorumTrue

for i in {1..50}; do
  n=$(hz rand -min 1 -max 5)

  hz driver Member${n}
  hz run shutdown
  hz driver "$(./setDrivers ${n})"
  hz run quorumFalse
  hz embeddedRestart Member${n}
  hz driver Member
  hz run quorumTrue

done