#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics

    gcViewerPics &> /dev/null || true
    hz-viewGc > gc.html || true

    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-server -XX:+PrintFlagsFinal -Xms3G -Xmx3G ${hzProps}"
hz clientOps "-server -XX:+PrintFlagsFinal -Xms500M -Xmx500M ${hzProps}"
hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box -upcwd hazelcast.keystore,hazelcast.truststore

hz run load
hz run validate

hz warmup 60
hz bench 300
hz run set
