#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run load
hz run addIdx
hz run validate

for version in 3.9 3.10 3.11 ; do

  hz submit get
  sleep 30

  for i in {1..4}; do
    sleep 10
    hz driver Member${i}
    hz run shutdown
    hz memberOps "-Xms2G -Xmx2G ${ops} -Dhazelcast.version=${version}"
    hz bounce Member${i}
    hz check
    sleep 10
  done

  ./changeVersion $(hz ip -id HZ Member1) ${version}
  sleep 10

  hz stop
  wait
  hz run validate

  hz bounce Client
done

hz run validate