#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size M4C4 -v ${hzVersion}  -ee -boxes a.box

hz bench 300

hz run atomic &
sleep 10
for i in {1..5}; do
  sleep 5
  n=$(( $(hz-random 4)+1 ))
  hz driver Member${n}
  hz run shutDown
  hz embeddedRestart Member${n}
done
wait
hz run validate

hz bounce -iterations 5  -iterationDelay 5 RandomMember &
hz run atomic
wait
hz run validate
