#!/usr/bin/env bash

clients=$1
members=$2
membersBox=$3
outputDir=$4

clusterId=G
version=1.5.0.final
initGgCulster ${clients} ${members} ${membersBox} ${clusterId} ${version}

benchid=putCache
clusterName=Grid

hzCmd load -id ${clusterId} -class gg.cache.PutBench -task ${benchid}

benchRun ${benchid} ${clusterName}

hzCmd download -dir ${outputDir}/${clusterName}-${version}

hzCmd wipe

