#!/usr/bin/env bash

benchId=$1
clusterName=$2

warmupSec=30
durationSec=60


for driver in Member; do

 hzCmd set  -id ${driver} -task ${benchId} -var warmupSec -val ${warmupSec}
 hzCmd set  -id ${driver} -task ${benchId} -var durationSec -val ${durationSec}

 hzCmd set  -id ${driver} -task ${benchId} -var keyDomain    -val 10000
 hzCmd set  -id ${driver} -task ${benchId} -var valueSetSize -val 1
 minVal=1001
 hzCmd set  -id ${driver} -task ${benchId} -var valueMinSize -val ${minVal}
 maxVal=1001
 hzCmd set  -id ${driver} -task ${benchId} -var valueMaxSize -val ${maxVal}

 for mapName in onheap; do
  hzCmd set  -id ${driver} -task ${benchId} -var name -val ${mapName}

  for threads in 8 ; do

    hzCmd set -id ${driver} -task ${benchId} -var title -val ${clusterName}${driver}-${mapName}-${benchId}-${threads}threads-values_min${minVal}-max${maxVal}
    hzCmd bench -id ${driver} -task ${benchId} -threads ${threads}

  done
 done
done
