#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true -Dhazelcast.connection.monitor.max.faults=1"
hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms3G -Xmx3G ${hzProps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms200M -Xmx400M ${hzProps}"
hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run load
hz run validate
hz run get &
sleep 30
  #hz freeze RandomMember -iterations 13 -restartDelay 180 -iterationDelay 25

  for i in {1..4}; do
    hz freeze Member${i} -restartDelay 180

    until hz run clusterSafe; do
      hz run validate || true
      sleep 10
    done
    hz run validate
  done

hz stop
wait
hz run validate
