#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="$mOps -Dhazelcast.hidensity.check.freememory=false"

cOps="$cOps -Dhazelcast.client.invocation.timeout.seconds=300"

hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms2G -Xmx2G ${ops} ${mOps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms500M -Xmx500M ${ops} ${cOps}"
hz cluster -size M4C5 -id HZ -v ${hzVersion} -ee -boxes a.box -user ec2-user

hz bench 7000
hz driver Client
hz run methodz &

for i in {1..75} ; do
    sleep 60
    hz run clusterShutdown
    hz embeddedRestart Member
    hz check
done
wait