#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    chartAll-JavaMetrics output
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}


ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops} -Dhazelcast.partition.count=2711"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size DM4C4 -v ${hzVersion} -ee -boxes a.box -user danny

hz run load
hz run validate
hz run get &
#hz run set &

sleep 300
hz kill Member1
sleep 900
hz restart Member1
sleep 900

hz stop
