#!/usr/bin/env bash

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
jvmProps="-XX:+PrintFlagsFinal -XX:+UseLargePages"

hz memberOps "${jvmProps} -Xms2G -Xmx2G ${hzProps}"
hz clientOps "${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hz cluster -size M4C4 -id HZ -v 3.7-SNAPSHOT   -type HZ -boxes a.box

hz memberOps "${jvmProps} -Xms2G -Xmx2G"
hz clientOps "${jvmProps} -Xms1G -Xmx1G"
hz cluster -size M4C4 -id GG -v 1.6.0-SNAPSHOT -type GG -boxes b.box

hz type Metrics
hz driver Member
hz threads 1
nohup hz run -id HZ -warmup false loadDataHz >> hz.out &
nohup hz run -id GG -warmup false loadDataGg >> gg.out &
wait

hz driver Client
hz threads 32
hz warmup 30
hz bench 60
nohup hz run -id HZ -warmup false getHz >> hz.out &
nohup hz run -id GG -warmup false getGg >> gg.out &
wait

hz wipe
hz chart compare -dir output -red HZ -blue GG
