#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?

    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4"}
user=${3:-ec2-user}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="$mOps -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz cluster -size ${size} -v ${hzVersion} -ee -boxes a.box -user ${user}

hz run load
hz run validate

for i in {1..35} ; do
    hz run clusterShutdown
    hz embeddedRestart Member
    hz check
done
hz run validate

hz bounce -iterations 75 -iterationDelay 1 Member
hz run validate