#!/usr/bin/env bash

gcArgs="$gcArgs -verbose:gc -Xloggc:verbosegc.log"
gcArgs="$gcArgs -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime"
hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
jvmProps="-XX:+PrintFlagsFinal -XX:+UseLargePages"

hzCmd set jhic
hzCmd set jhicArgs -d 960 -i 1000


benchJar=$(find ~/.m2 -name hzCmd-bench-1.0.0.jar)

hzCmd set memberOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hzCmd set clientOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hzCmd init cluster -size XS -id HZ  -v 3.6.2 -ee true  -type HZ -uplib ${benchJar} -boxes boxes-a

hzCmd set memberOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G"
hzCmd set clientOps "${gcArgs} ${jvmProps} -Xms1G -Xmx1G"
hzCmd init cluster -size XS -id GG  -v 1.5.0.final     -type GG -uplib ${benchJar} -boxes boxes-b

hzCmd bench type Hdr
hzCmd bench driver Client
hzCmd bench threads 8
hzCmd bench interval 1
hzCmd bench warmup 900
hzCmd bench duration 10800
nohup hzCmd bench run -cluster HZ -b setHZ >> outHZ.txt &
nohup hzCmd bench run -cluster GG -b putGG >> outIG.txt &
wait
hzCmd wipe

hzCmd chart compare -dir output -red HZ -blue GG

hzCmd processJhic -dir output
hzCmd chart compairHdr -dir output -red Member-HZ -blue Member-GG
hzCmd chart compairHdr -dir output -red Client-HZ -blue Client-GG

cp go output/
mv *.txt output/
mv nohup.out output/
