#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hz cluster -size M4C4 -v 3.7,3.7.1,3.7.2,3.7.3 -ee -boxes a.box

hz run load
hz run validate

for version in 3.7 3.7.1 3.7.2 3.7.3; do
  hz run get &

  for i in {1..4}; do
    sleep 10
    hz driver Member${i}
    hz run shutdown
    hz bounce -v ${version} Member${i}
    sleep 10
  done

  hz stop
  wait
  hz run validate

  hz bounce -v ${version} Client
done

hz run validate