#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

ec2Type="c4.2xlarge"
aws-create --count 5 --instanceType ${ec2Type} --outputFile a.box
aws-create --count 5 --instanceType ${ec2Type} --outputFile b.box
aws-create --count 5 --instanceType ${ec2Type} --outputFile c.box
aws-create --count 5 --instanceType ${ec2Type} --outputFile d.box
aws-create --count 5 --instanceType ${ec2Type} --outputFile e.box

ops="${ops} -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
ops="${ops} -Dhazelcast.enterprise.wanrep.batch.size=150"

mOps="${mOps} -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000 -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="${mOps} -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30 -Dhazelcast.rest.enabled=true"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hzVersion="3.8-SNAPSHOT"
hz cluster -id A -size M5C10 -v ${hzVersion} -ee -boxes a.box
hz cluster -id B -size M5C10 -v ${hzVersion} -ee -boxes b.box
hz cluster -id C -size M5C10 -v ${hzVersion} -ee -boxes c.box
hz cluster -id D -size M5C10 -v ${hzVersion} -ee -boxes d.box
hz cluster -id E -size M5C10 -v ${hzVersion} -ee -boxes e.box

#  A-----B
#  | \  /|
#  |  C  |
#  | /  \|
#  D-----E
hz wan A B D C
hz wan B E A C
hz wan E D B C
hz wan D A E C
hz wan C A B D E
hz bounce Member

hz run -id C ops/load
sleep 30
hz run ops/validate
hz run ops/clusterShutdown
hz embeddedRestart Member
hz run ops/validate

hz run -id C ops/clusterShutdown
hz run -id A ops/remove_load
sleep 10
hz run -id '(A|B|D|E)' ops/validateSize0
sleep 30
hz embeddedRestart -id C Member
hz run -id C ops/validate


./syncMapsToABDE $(hz ip -id C Member1)
sleep 60
hz run ops/validate