#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

ec2Type="c4.2xlarge"
aws-create --count 2 --instanceType ${ec2Type} --outputFile a.box
aws-create --count 2 --instanceType ${ec2Type} --outputFile b.box
aws-create --count 2 --instanceType ${ec2Type} --outputFile c.box
aws-create --count 2 --instanceType ${ec2Type} --outputFile d.box
aws-create --count 2 --instanceType ${ec2Type} --outputFile e.box

ops="${ops} -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
ops="${ops} -Dhazelcast.enterprise.wanrep.batch.size=150"

mOps="${mOps} -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000 -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="${mOps} -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30 -Dhazelcast.rest.enabled=true"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hzVersion=${1:-$(hazelcastVersion)}
hz cluster -id A -size M2C4 -v ${hzVersion} -ee -boxes a.box
hz cluster -id B -size M2C4 -v ${hzVersion} -ee -boxes b.box
hz cluster -id C -size M2C4 -v ${hzVersion} -ee -boxes c.box
hz cluster -id D -size M2C4 -v ${hzVersion} -ee -boxes d.box
hz cluster -id E -size M2C4 -v ${hzVersion} -ee -boxes e.box

echo '  WAN  '
echo 'A-----B'
echo '| \  /|'
echo '|  C  |'
echo '| /  \|'
echo 'D-----E'
hz wan A B D C
hz wan B E A C
hz wan E D B C
hz wan D A E C
hz wan C A B D E
hz bounce Member

for i in {0..10} ; do
  echo 'load C with data validate replication'
  hz run -id C ops/load
  sleep 30
  hz run ops/validate
  echo 'remove data from C validate replication'
  hz run -id C ops/remove_load
  sleep 30
  hz run ops/validateSize0
done


for i in {0..10} ; do
  echo 'shutdown all clusters validate hot restart data'
  hz run ops/clusterShutdown
  hz embeddedRestart Member
  hz run ops/validate
done


for i in {0..10} ; do
  echo 'clear data from (A|B|D|E) and wan sync from C'
  hz run -id '(A|B|D|E)' ops/clear
  sleep 10
  hz run -id '(A|B|D|E)' ops/validateSize0
  hz run -id C ops/validate
  ./syncMapsToABDE $(hz ip -id C Member1)
  hz run -id '(A|B|D|E)' ops/validate
done



echo 'shutdown C and remove data from A validate data removed from (A|B|D|E)'
hz run -id C ops/clusterShutdown
hz run -id A ops/remove_load
sleep 30
hz run -id '(A|B|D|E)' ops/validateSize0

echo 'restart C validate data loaded by C at hot restart, is cleared by queued remove events'
hz embeddedRestart -id C Member
sleep 60
hz run -id 'C' ops/validateSize0


echo 'load C with data validate replication'
hz run -id C ops/load
sleep 30
hz run ops/validate



