#!/usr/bin/env bash

ip=$1;

    for group in A B D E ; do
        curl -H "Content-type: text/plain" -X POST -d "wanReplication&${group}&mapBak1HD" --URL http://${ip}:5701/hazelcast/rest/wan/sync/map
    done
