#!/usr/bin/env bash

ip=$1;

for group in A B D E ${hzVersion} ; do
    curl -H "Content-type: text/plain" -X POST -d "wanReplication&${group}" --URL http://${ip}:5701/hazelcast/rest/wan/sync/allmaps
    sleep 20
done