#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="$mOps -Dhazelcast.hidensity.check.freememory=false"
mOps="$mOps -Dhazelcast.rest.enabled=true"
mOps="$mOps -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30"

hz memberOps "-Xms2G -Xmx2G ${ops} ${mOps}"
hz clientOps "-Xms500M -Xmx500M ${ops}"
hz cluster -size M4C5 -id HZ -v ${hzVersion} -ee -boxes a.box -user ec2-user

hz driver Client
hz run ops &


for i in {0..10} ; do
 echo "snapshot while clients make operations ${i}"
 hz run snapShotStart
 hz run snapShotEnd
done
hz bash -jvmId Member "rm -fr /home/ec2-user/hot-backup/*"


for i in {0..10} ; do
 echo "snapshot, restart while clients make operations ${i}"
 hz run snapShotStart
 hz run snapShotEnd
 hz run clusterShutdown
 ./mvHotFiles
 hz embeddedRestart Member
done

hz stop
wait

hz run clearCaches
hz run clearMaps
sleep 10
echo "load cluster data. snapshot, restart, validate"
for i in {0..50} ; do
 hz run load
 hz run validate

 hz run snapShotStart
 hz run snapShotEnd
 hz run clusterShutdown
 ./mvHotFiles
 hz embeddedRestart Member
 hz run validate
done
