#!/usr/bin/env bash

benchJar=$(find ~/.m2 -name hzCmd-bench-1.0.0.jar)
hzCmd uploadlib -id Gg.* -src ${benchJar}

hzCmd load -id Gg.* -class gg.cache.GetBench -task get
hzCmd load -id Gg.* -class gg.cache.PutBench -task put

./benchRun get
./benchRun put
./benchRun "get|put"