#!/usr/bin/env bash


benchJar=$(find ~/.m2 -name hzCmd-bench-1.0.0.jar)
hzCmd uploadlib -id Hz.* -src ${benchJar}

hzCmd load -id Hz.* -class hz.imap.GetBench -task get
hzCmd load -id Hz.* -class hz.imap.PutBench -task put

./benchRun get
./benchRun put
./benchRun "get|put"