#!/usr/bin/env bash

hz memberOps "-Xms1G -Xmx1G"
hz clientOps "-Xms500M -Xmx500M"
hz cluster -size M4C4 -v 3.6,3.6.1,3.6.2,3.6.3,3.6.4,3.6.5 -boxes a.box

hz run load

for version in 3.6.1 3.6.2 3.6.3 3.6.4 3.6.5 ; do
  hz run putGet &

  for i in {1..4}; do
    sleep 300
    hz driver Member${i}
    hz run shutDown
    hz bounce -v ${version} Member${i}
    sleep 300
  done

  hz bounce -v ${version} Client
done

hz run sizeCheck
hz download
hz wipe

chartAll-JavaMetrics output
