#!/usr/bin/env bash

hz memberOps "-Xms300M -Xmx300M"
hz clientOps "-Xms50M -Xmx50M"
hz cluster -size DM2C2 -v 3.6,3.6.1,3.6.2,3.6.3,3.6.4,3.6.5 -boxes a.box

hz run load
hz run putGet &
sleep 21

for version in 3.6.1 3.6.2 3.6.3 3.6.4 3.6.5 ; do

  for i in {1..2}; do
    hz driver Member${i}
    hz run shutDown
    hz bounce -v ${version} Member${i}
    sleep 21
  done
  sleep 21

  hz bounce -v ${version} Client
  hz run putGet &
  sleep 21
done

sleep 21
hz run sizeCheck
hz download
hz wipe

chartAll-JavaMetrics output
