#!/usr/bin/env bash

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms500M -Xmx500M ${ops}"

hz cluster -size M4C4 -v 3.6,3.6.1,3.6.2,3.6.3,3.6.4,3.6.5 -ee -boxes a.box

hz run load
hz run validate-load

for version in 3.6.1 3.6.2 3.6.3 3.6.4 3.6.5 ; do
  hz run methodz &

  for i in {1..4}; do
    sleep 10
    hz driver Member${i}
    hz run shutdown
    hz bounce -v ${version} Member${i}
    sleep 10
  done

  hz stop
  wait
  hz run validate-load
  hz run validate-atomic

  hz bounce -v ${version} Client
done

hz download
hz wipe

chartAll-JavaMetrics output
