#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz wipe
    chartAll-JavaMetrics output
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

hz broker -ip 10.212.1.107

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"

gcOps="${gcOps} -XX:+UseG1GC -XX:+UseTLAB -XX:MaxMetaspaceSize=512m -XX:+AlwaysPreTouch"
gcOps="${gcOps} -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=20 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20"

hz memberOps "-server -Xms8G -Xmx8G ${gcOps} ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size DM3C2000 -v 3.7.2 -ee -boxes a.box -user danny


hz bench 600
hz run load
hz run validate
hz run info
hz run ops
#hz submit put
#hz submit clear
sleep 30
hz run info

hz stop
