#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?

    hz-ssh a.box 'df -h' ec2-user

    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz cluster -size M4 -id HZ -v ${hzVersion} -ee -boxes a.box -user ec2-user

hz run load
hz run validate

hz run clusterShutdown
hz embeddedRestart Member1
hz embeddedRestart Member2
hz embeddedRestart Member3
hz run validate

hz run clusterShutdown
hz embeddedRestart Member1
hz embeddedRestart Member2
hz run validate

hz run clusterShutdown
hz embeddedRestart Member1
hz run validate
