#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4C4"}
user=${3:-ec2-user}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms3G -Xmx3G ${hzProps}"
hz clientOps "-Xms400M -Xmx400M ${hzProps}"
hz cluster -ee -size ${size} -v ${hzVersion} -boxes a.box -user ${user}

hz run fill
hz run validate
hz run add &

for j in {1..30}; do
 for i in {1..3}; do
  sleep 5
  hz driver Member${i}
  hz run shutDown
  hz check
 done

 for i in {1..3}; do
  hz embeddedRestart Member${i}
 done
done

hz stop
wait
hz run validate