#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4C4"}
user=${3:-ec2-user}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"

mOps="$mOps -Dhazelcast.cache.invalidation.batch.size=1000"
mOps="$mOps -Dhazelcast.cache.invalidation.batchfrequency.seconds=5"
mOps="$mOps -Dhazelcast.map.invalidation.batch.size=1000"
mOps="$mOps -Dhazelcast.map.invalidation.batchfrequency.seconds=5"

cOps="$cOps -Dhazelcast.invalidation.max.tolerated.miss.count=0"
cOps="$cOps -Dhazelcast.invalidation.reconciliation.interval.seconds=30"

hz memberOps "-Xms2G -Xmx2G ${ops} ${mOps}"
hz clientOps "-Xms500M -Xmx500M ${ops} ${cOps}"
hz cluster -ee -size ${size} -v ${hzVersion} -boxes a.box -user ${user}

hz run load
hz run validate
hz run ops-lab
hz check