#!/usr/bin/env bash

ip=$1
version=$2

echo "curl -H  Content-type: text/plain  -X POST -d  HZ&HZ&${version}  --URL http://${ip}:5701/hazelcast/rest/management/cluster/changeVersion"

      curl -H "Content-type: text/plain" -X POST -d "HZ&HZ&${version}" --URL http://${ip}:5701/hazelcast/rest/management/cluster/changeVersion
