#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run load
hz run addIdx
hz run validate
hz driver Client
hz run get &
hz run put &

for version in 3.9 3.10 3.11 ; do
  for i in {1..4}; do
    sleep 15
    hz driver Member${i}
    hz run shutdown
    hz kill Member${i}
    hz memberOps "-Xms2G -Xmx2G ${ops} -Dhazelcast.internal.override.version=${version}"
    hz relaunch Member${i}

    hz driver Member${i}
    hz run get &
    hz run put &
    sleep 15
  done
  ./changeVersion $(hz ip -id HZ Member1) ${version}
done

hz run validate
hz check