#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4C4"}
user=${3:-ec2-user}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size M4C4 -v ${hzVersion}  -ee -boxes a.box

hz run txn &
sleep 10
for i in {1..50}; do
  sleep 5
  n=$(( $(od -An -tu -N2 /dev/urandom) % 4 + 1))
  hz driver Member${n}
  hz run shutDown
  hz embeddedRestart Member${n}
  hz check
done

hz stop
wait
hz run validate
