#!/usr/bin/env bash

hz-ssh a.box 'sudo bash -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"' ec2-user

hz warmup 300
hz bench 900

hz clientOps "-Xms1G -Xmx1G"
hz cluster -size M6C6 -id RED -v 3.2.3 -type RED -boxes a.box -user ec2-user

hz run fillRed
hz run methodsRed

hz download
hz wipe
hz-ssh a.box 'killall -9 redis-server' ec2-user


hz warmup 300
hz bench 900

hz clientOps "-Xms1G -Xmx1G"
hz memberOps "-Xms3G -Xmx3G -Dhazelcast.backpressure.enabled=true"
hz cluster -size M6C6 -id HZ -v 3.7.1 -type HZ -boxes a.box -user ec2-user

hz run fillHz
hz run methodsHz

hz download
hz wipe


chart-ComparisonMetrics output RED HZ
