#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dhazelcast.hotrestart.gc.stuck.detect.threshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"

hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms2G -Xmx2G ${ops} ${mOps}"
hz cluster -size M4 -id HZ -v 3.7 -ee -boxes a.box -user ec2-user

hz run load
hz run validateLoad

for i in {1..10} ; do
    hz run clusterShutdown
    hz embeddedRestart Member
    hz run active
    hz check
done
wait