#!/usr/bin/env bash

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
jvmProps="-XX:+PrintFlagsFinal -XX:+UseLargePages"

hz set jhic
hz set jhicArgs -d 960 -i 1000


hz memberOps "${jvmProps} -Xms10G -Xmx10G ${hzProps}"
hz clientOps "${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hz cluster -size M4C4 -id ONHEAP  -v 3.6.2           -type HZ -boxes a.box

hz memberOps "${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hz clientOps "${jvmProps} -Xms1G -Xmx1G ${hzProps}"
hz cluster -size M4C4 -id OFFHEAP -v 3.6.2 -ee true  -type HZ -boxes b.box

hz type Hdr
hz driver Client
hz threads 8
hz interval 1
hz warmup 900
hz bench 10800
nohup hz run -id ONHEAP  setOnHeap  >> on.out &
nohup hz run -id OFFHEAP setOffHeap >> off.out &
wait
hz wipe

hz chart compare -dir output -red ONHEAP -blue OFFHEAP

hz processJhic -dir output
hz chart compairHdr -dir output -red Member-ONHEAP -blue Member-OFFHEAP
hz chart compairHdr -dir output -red Client-ONHEAP -blue Client-OFFHEAP

