#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4C4"}
user=${3:-ec2-user}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms3G -Xmx3G ${hzProps}"
hz clientOps "-Xms400M -Xmx400M ${hzProps}"
hz cluster -ee -size ${size} -v ${hzVersion} -boxes a.box -user ${user}

hz run load
hz run validate
hz run get &

memberCount=$(hz memberCount)

for j in {1..15}; do

 for (( m=2; m<=${memberCount}; m++ )) ; do
  sleep 20
  hz driver Member${m}
  hz run shutDown
  hz check
 done

 for (( m=2; m<=${memberCount}; m++ )) ; do
  hz embeddedRestart Member${m}
 done

 hz driver Member1
 hz run shutDown
 hz embeddedRestart Member1

done

hz stop
wait
hz run validate