#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true -Dhazelcast.connection.monitor.max.faults=1"
hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms3G -Xmx3G ${hzProps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms200M -Xmx400M ${hzProps}"
hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run load
hz run validate
hz run get &

for j in {1..15}; do
 for i in {1..3}; do
  sleep 20
  hz driver Member${i}
  hz run shutDown
  hz check
 done

 for i in {1..3}; do
  hz embeddedRestart Member${i}
 done
done

hz stop
wait
hz run validate