#!/usr/bin/env bash

set -e

iterations=${1:-25}
sleep 30
memberCount=$(hz memberCount)

for (( i=0; i<=${iterations}; i++ )) ; do

 for (( m=2; m<=${memberCount}; m++ )) ; do
  hz driver Member${m}
  hz run shutDown


  sleep 60
  #hz driver Member1
  #until hz run clusterSafe; do
   #sleep 5
  #done

 done

 for (( m=2; m<=${memberCount}; m++ )) ; do
  hz embeddedRestart Member${m}
 done

 #hz driver Member"2"
 #until hz run clusterSafe; do
 # sleep 5
 #done
 sleep 60

 hz driver Member1
 hz run shutDown
 hz embeddedRestart Member1

 hz check
done