#!/usr/bin/env bash

hzOps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms4G -Xmx4G ${hzOps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms1G -Xmx1G ${hzOps}"
hz cluster -size M4C4 -id NEW -v 3.7-SNAPSHOT -type HZ -boxes a.box
hz cluster -size M4C4 -id OLD -v 3.6.3        -type HZ -boxes b.box

hz driver Client,Member
hz type Metrics
hz interval 1
hz threads 1
hz warmup 30
hz bench 60

nohup hz run -id NEW put > new.out &
nohup hz run -id OLD put > old.out &
wait
hz wipe

chart-ComparisonMetrics output NEW OLD
cp go output/
mv *.out output/
