#!/usr/bin/env bash

hzOps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms3G -Xmx3G ${hzOps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms1G -Xmx2G ${hzOps}"

hz cluster -size M4C4 -id NEW -v 3.7-SNAPSHOT -ee -type HZ -boxes a.box
hz cluster -size M4C4 -id OLD -v 3.6.3        -ee -type HZ -boxes b.box

hz driver Client,Member
hz type Metrics
hz interval 1
hz threads 8
hz warmup 60
hz bench 300

nohup hz run -id NEW putAll > new.out &
nohup hz run -id OLD putAll > old.out &
wait
hz wipe

chart-ComparisonMetrics output NEW OLD

cp go output/
mv *.out output/
