#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run map-lock &

for j in {1..15}; do
 for i in {1..3}; do
  sleep 20
  hz driver Member${i}
  hz run shutDown
  hz check
 done

 for i in {1..3}; do
  hz embeddedRestart Member${i}
 done
done

hz stop
wait
hz run validate
