#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT


#Case 1: cluster: 3.7, 3.7.1, 3.7.2, 3.7.3              clients: 3.7.x
hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms500M -Xmx500M ${hzProps}"
hz clientOps "-Xms100M -Xmx100M ${hzProps}"

hz cluster -size M1 -v 3.7            -ee -boxes a.box
hz cluster -size M1 -v 3.7.1          -ee -boxes a.box
hz cluster -size M1 -v 3.7.2          -ee -boxes a.box
hz cluster -size M1 -v 3.7.3          -ee -boxes a.box

hz cluster -size C1 -v 3.7            -ee -boxes a.box
hz cluster -size C1 -v 3.7.1          -ee -boxes a.box
hz cluster -size C1 -v 3.7.2          -ee -boxes a.box
hz cluster -size C1 -v 3.7.3          -ee -boxes a.box

hz bench 1800
hz driver Client
hz run createUseDestroy
hz driver HZ
hz run createUseDestroy
hz download -dir output-case-1
hz wipe



#Case 2: cluster: 3.7.3                                  clients: 3.6.x and 3.7.3
hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms500M -Xmx500M -Dhazelcast.compatibility.3.6.client=true ${hzProps}"
hz clientOps "-Xms100M -Xmx100M ${hzProps}"

hz cluster -size M4 -v 3.7.3          -ee -boxes a.box

hz cluster -size C1 -v 3.7.3          -ee -boxes a.box
hz cluster -size C1 -v 3.6            -ee -boxes a.box
hz cluster -size C1 -v 3.6.1          -ee -boxes a.box
hz cluster -size C1 -v 3.6.2          -ee -boxes a.box
hz cluster -size C1 -v 3.6.3          -ee -boxes a.box
hz cluster -size C1 -v 3.6.4          -ee -boxes a.box
hz cluster -size C1 -v 3.6.5          -ee -boxes a.box
hz cluster -size C1 -v 3.6.6          -ee -boxes a.box

hz bench 1800
hz driver Client
hz run createUseDestroy
hz driver HZ
hz run createUseDestroy
hz download -dir output-case-2
hz wipe


#Case 3: cluster 3.6.x                                   clients: 3.6.x and 3.7.3
hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms500M -Xmx500M ${hzProps}"
hz clientOps "-Xms100M -Xmx100M -Dhazelcast.compatibility.3.6.server=true ${hzProps}"

hz cluster -size M1 -v 3.6            -ee -boxes a.box
hz cluster -size M1 -v 3.6.1          -ee -boxes a.box
hz cluster -size M1 -v 3.6.2          -ee -boxes a.box
hz cluster -size M1 -v 3.6.3          -ee -boxes a.box
hz cluster -size M1 -v 3.6.4          -ee -boxes a.box
hz cluster -size M1 -v 3.6.5          -ee -boxes a.box
hz cluster -size M1 -v 3.6.6          -ee -boxes a.box

hz cluster -size C1 -v 3.7.3          -ee -boxes a.box
hz cluster -size C1 -v 3.6            -ee -boxes a.box
hz cluster -size C1 -v 3.6.1          -ee -boxes a.box
hz cluster -size C1 -v 3.6.2          -ee -boxes a.box
hz cluster -size C1 -v 3.6.3          -ee -boxes a.box
hz cluster -size C1 -v 3.6.4          -ee -boxes a.box
hz cluster -size C1 -v 3.6.5          -ee -boxes a.box
hz cluster -size C1 -v 3.6.6          -ee -boxes a.box


hz bench 1800
hz driver Client
hz run createUseDestroy
hz driver HZ
hz run createUseDestroy
hz download -dir output-case-3
hz wipe