#!/usr/bin/env bash

hz broker -ip 10.212.1.107

hzOps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms4G -Xmx4G ${hzOps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms1G -Xmx1G ${hzOps}"

hz cluster -size M8 -id HZ -v 3.7-SNAPSHOT -type HZ -ee true -boxes a.box -user danny

for i in {1..32} ; do

    hz type Metrics
    hz interval 0
    hz threads 64
    hz bench 900
    hz driver Member
    hz run -id HZ -warmup false set

    hz threads 1
    hz driver Member1
    hz run -id HZ -warmup false clusterShutdown
    hz embeddedRestart -id Member
    hz run -id HZ -warmup false active

done

hz download

hz wipe
hz-ssh a.box 'rm -r hot-junk' danny

cp go output/
mv *.out output/
