#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

ec2Type="c4.2xlarge"
aws-create -count 5 --instanceType ${ec2Type} --outputFile a.box
aws-create -count 5 --instanceType ${ec2Type} --outputFile b.box
aws-create -count 5 --instanceType ${ec2Type} --outputFile c.box
aws-create -count 5 --instanceType ${ec2Type} --outputFile d.box
aws-create -count 5 --instanceType ${ec2Type} --outputFile e.box

ops="${ops} -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
ops="${ops} -Dhazelcast.enterprise.wanrep.batch.size=150"
hz memberOps "-Xms4G -Xmx4G ${ops}"
hz clientOps "-Xms200M -Xmx400M ${ops}"

hzVersion="3.8-SNAPSHOT"
hz cluster -id A -size M5C10 -v ${hzVersion} -ee -boxes a.box
hz cluster -id B -size M5C10 -v ${hzVersion} -ee -boxes b.box
hz cluster -id C -size M5C10 -v ${hzVersion} -ee -boxes c.box
hz cluster -id D -size M5C10 -v ${hzVersion} -ee -boxes d.box
hz cluster -id E -size M5C10 -v ${hzVersion} -ee -boxes e.box

hz wan A B C D E
hz bounce

hz run -id A load
sleep 10
hz run validate
hz run clusterShutdown
hz embeddedRestart Member

until hz run clusterSafe; do
    sleep 10
done
hz run validate



hz run -id A clusterShutdown
hz embeddedRestart -id A Member

ipMember1A="someip";
for i in {0..8} ; do
    for group in B C D E ${hzVersion} ; do
        curl -H "Content-type: text/plain" -X POST -d "wanReplication&${group}&mapBak1HD${i}" --URL http://${ipMember1A}:5701/hazelcast/rest/wan/sync/map
    done
done