#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"

mOps="$mOps -Dhazelcast.cache.invalidation.batch.size=1000"
mOps="$mOps -Dhazelcast.cache.invalidation.batchfrequency.seconds=5"
mOps="$mOps -Dhazelcast.map.invalidation.batch.size=1000"
mOps="$mOps -Dhazelcast.map.invalidation.batchfrequency.seconds=5"

cOps="$cOps -Dhazelcast.invalidation.max.tolerated.miss.count=1"
cOps="$cOps -Dhazelcast.invalidation.reconciliation.interval.seconds=30"

hz memberOps "-Xms2G -Xmx2G ${ops} ${mOps}"
hz clientOps "-Xms500M -Xmx500M ${ops} ${cOps}"
hz cluster -size M4C8 -id HZ -v ${hzVersion} -ee -boxes a.box -user ec2-user

hz run load
hz run validate

hz driver Client
hz run ops &
sleep 30
hz driver Member
hz submit ops
sleep 30
for i in {1..100}; do
    n=$(hz rand -min 1 -max 5)
    hz bounce -iterationDelay 5 -restartDelay 5 Member${n}
    hz driver Member${n}
    hz submit ops
    hz check
done

hz run validate
