#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms500M -Xmx500M ${hzProps}"
hz clientOps "-Xms100M -Xmx100M ${hzProps}"
hz cluster -size M1 -v 3.6   -ee -boxes a.box
hz cluster -size M1 -v 3.6.1 -ee -boxes a.box
hz cluster -size M1 -v 3.6.2 -ee -boxes a.box
hz cluster -size M1 -v 3.6.3 -ee -boxes a.box
hz cluster -size M1 -v 3.6.4 -ee -boxes a.box
hz cluster -size M1 -v 3.6.5 -ee -boxes a.box
hz cluster -size M1 -v 3.6.6 -ee -boxes a.box

hz cluster -size C1 -v 3.6   -ee -boxes a.box
hz cluster -size C1 -v 3.6.1 -ee -boxes a.box
hz cluster -size C1 -v 3.6.2 -ee -boxes a.box
hz cluster -size C1 -v 3.6.3 -ee -boxes a.box
hz cluster -size C1 -v 3.6.4 -ee -boxes a.box
hz cluster -size C1 -v 3.6.5 -ee -boxes a.box
hz cluster -size C1 -v 3.6.6 -ee -boxes a.box

hz run load
hz run validate

hz bench 900
hz driver Member
hz run get
hz driver Client
hz run get
