#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${hzProps}"
hz clientOps "-Xms1G -Xmx1G ${hzProps}"
hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run load
hz run addIdx
hz run validate

hz bench 2700
hz run getRemoveAllPut
