#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    hz-ssh a.box 'rm -r hot-junk' danny
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT


ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dcom.hazelcast.spi.hotrestart.gc.stuckDetectThreshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="$mOps -Dhazelcast.hidensity.check.freememory=false"
mOps="$mOps -Dhazelcast.operation.thread.count=4"

hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms1G -Xmx1G ${ops}"

hz cluster -size M4C100 -id HZ -v 3.7 -ee -boxes a.box -user danny

for i in {1..288} ; do
    hz bench 600
    hz driver Client
    hz run methods &
    sleep 300
    hz run clusterShutdown
    hz embeddedRestart Member
    hz run active
    hz check
    wait
done
