#!/usr/bin/env bash
set -e

hz broker -ip 10.212.1.107

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dcom.hazelcast.spi.hotrestart.gc.stuckDetectThreshold=10000"
mOps="$mOps -Dhazelcast.hotrestart.free.native.memory.percentage=15"
mOps="$mOps -Dhazelcast.hidensity.check.freememory=false"
mOps="$mOps -Dhazelcast.operation.thread.count=4"

hz memberOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-XX:+PrintFlagsFinal -XX:+UseLargePages -Xms1G -Xmx1G ${ops}"

hz cluster -size M4C4 -id HZ -v 3.7 -ee -boxes a.box -user danny

for i in {1..32} ; do
    hz bench 900
    hz driver Client
    hz run opps &
    sleep 300
    hz run clusterShutdown
    hz embeddedRestart -id Member
    hz run active
    wait
done

hz download

hz wipe
hz-ssh a.box 'rm -r hot-junk' danny

cp go output/
mv *.out output/
