#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -size M4C4 -v ${hzVersion} -ee -boxes a.box

hz run atomic &
sleep 120
for i in {1..10}; do
    hz freeze RandomMember -restartDelay 180

    until hz run clusterSafe; do
      sleep 10
    done
done

sleep 10
hz stop
wait
hz run validate
