#!/usr/bin/env bash

set -e
cleanup() {
    hz download
    hz wipe
}
trap "cleanup" INT TERM EXIT

hz broker -ip 10.212.1.107

hz memberOps "-Xms500M -Xmx500M"
hz clientOps "-Xms200M -Xmx200M"
hz cluster -size M3C100 -v 3.7 -boxes local.box -user danny

hz driver Client
hz type Metrics
hz threads 8

hz submit put

for x in {1..500}; do
 for i in {1..9}; do
  sleep 5
  hz kill Client${i}
  hz restart Client${i}
  hz driver Client${i}
  hz submit put
  hz check
 done
done
