#!/usr/bin/env bash

set -e
cleanup() {
    hz download
    hz wipe
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4C4"}
user=${2:-ec2-user}

hz memberOps "-Xms500M -Xmx500M"
hz clientOps "-Xms200M -Xmx200M"
hz cluster -size ${size} -v ${hzVersion} -boxes a.box -user ${user}

hz driver Client
hz type Metrics
hz threads 8

hz submit put

for x in {1..100}; do
 for i in {1..9}; do
  sleep 5
  hz kill Client${i}
  hz restart Client${i}
  hz driver Client${i}
  hz submit put
  hz bounce -restartDelay 5 RandomMember
  hz check
 done
done
