#!/usr/bin/env bash

set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms500M -Xmx500M -Dhazelcast.compatibility.3.6.client=true ${hzProps}"
hz clientOps "-Xms100M -Xmx100M -Dhazelcast.compatibility.3.6.server=true ${hzProps}"
hz cluster -size M4 -v ${hzVersion} -ee -boxes a.box
#hz cluster -size M1 -v 3.7          -ee -boxes a.box
#hz cluster -size M1 -v 3.7.1        -ee -boxes a.box
#hz cluster -size M1 -v 3.7.2        -ee -boxes a.box

hz cluster -size C1 -v ${hzVersion} -ee -boxes a.box
hz cluster -size C1 -v 3.6          -ee -boxes a.box
hz cluster -size C1 -v 3.6.1        -ee -boxes a.box
hz cluster -size C1 -v 3.6.2        -ee -boxes a.box
hz cluster -size C1 -v 3.6.3        -ee -boxes a.box
hz cluster -size C1 -v 3.6.4        -ee -boxes a.box
hz cluster -size C1 -v 3.6.5        -ee -boxes a.box
hz cluster -size C1 -v 3.6.6        -ee -boxes a.box

hz bench 300
hz driver Client
hz run createDestroy
hz driver HZ
hz run createDestroy


#hz run load
#hz run validate

#hz driver Member
#hz run get
#hz driver Client
#hz run get
