#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}
size=${2:-"M4C4"}
user=${2:-ec2-user}

ops="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
hz memberOps "-Xms2G -Xmx2G ${ops}"
hz clientOps "-Xms400M -Xmx400M ${ops}"
hz cluster -ee -size ${size} -v ${hzVersion} -boxes a.box -user ${user}

hz run atomic &
sleep 10
for i in {1..50}; do
  sleep 5
  member=$(hz randMember)
  hz driver ${member}
  hz run shutDown
  hz embeddedRestart ${member}
  hz check
done

hz stop
wait
hz run validate
