#!/usr/bin/env bash

clients=$1
members=$2
membersBox=$3
outputDir=$4

mapName=hzAsyncOnheap

clusterId=H
version=3.6
./initHzCulster ${clients} ${members} ${membersBox} ${clusterId} ${version}

benchid=setMap
clusterName=Hz

hzCmd load -id ${clusterId} -class hz.imap.SetBench -task ${benchid}

./benchRun ${benchid} ${clusterName} ${mapName}

hzCmd download -dir ${outputDir}/${clusterName}-${version}

hzCmd wipe
