#!/usr/bin/env bash

clients=$1
members=$2
membersBox=$3
outputDir=$4

cacheName=atomic

clusterId=G
version=1.5.0.final
./initGgCulster ${clients} ${members} ${membersBox} ${clusterId} ${version}

benchid=putCache
clusterName=Gg

hzCmd load -id ${clusterId} -class gg.cache.PutBench -task ${benchid}

./benchRun ${benchid} ${clusterName} ${cacheName}

hzCmd download -dir ${outputDir}/${clusterName}-${version}

hzCmd wipe

