#!/usr/bin/env bash

hzProps="-Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"

hz memberOps "-Xms2G -Xmx2G ${hzProps}"
hz clientOps "-Xms1G -Xmx1G ${hzProps}"
hz cluster -size M2C2 -id HZ -v 3.7.2 -type HZ -boxes a.box

hz memberOps "-Xms2G -Xmx2G"
hz clientOps "-Xms1G -Xmx1G"
hz cluster -size M2C2 -id CO -v 12.2.1 -type CO -boxes b.box


hz type Metrics
hz driver Client
hz threads 8
hz warmup 60
hz bench 300

nohup hz run -id HZ putHZ >> outHZ.txt &
nohup hz run -id GG putCO >> outCO.txt &
wait
hz download
hz wipe

hz chart compare -dir output -red HZ -blue CO
