#!/usr/bin/env bash
set -e
cleanup() {
    exitCode=$?
    hz download || true
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

hzVersion=${1:-$(hazelcastVersion)}

ops="$ops -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY}"
ops="$ops -Dhazelcast.backpressure.enabled=true"
ops="$ops -ea"

mOps="$mOps -Dhazelcast.cache.invalidation.batch.size=1000"
mOps="$mOps -Dhazelcast.cache.invalidation.batchfrequency.seconds=5"

hz memberOps "-Xms2G -Xmx2G ${ops} ${mOps}"
hz clientOps "-Xms500M -Xmx500M ${ops}"
hz cluster -size M4C40 -id HZ -v ${hzVersion} -ee -boxes a.box -user ec2-user

hz run load
hz bench 3600
hz driver Client
hz run methods
wait