#!/usr/bin/env bash

iterations=${1:-25}
sleep 30
memberCount=$(hz memberCount)

for (( i=0; i<=${iterations}; i++ )) ; do

 for (( m=2; m<=${memberCount}; m++ )) ; do
  hz driver Member${m}
  hz run shutDown
 done

 for (( m=2; m<=${memberCount}; m++ )) ; do
  hz embeddedRestart Member${m}
 done

 hz driver Member1
 hz run shutDown
 hz embeddedRestart Member1

done